### PR TITLE
Simplify get_short_name regex

### LINKED ISSUE #29: Conda packages hang
It seems there is an issue with the regular expression here: https://github.com/joshuagryphon/plastid/blob/master/plastid/util/io/openers.py#L253

When conda packages are built and tested, the paths can be rather long and it seems that this is hanging. I'm not quite sure what the intent of the code is, but I suspect it could be simplified using some `os.path` functions.

### PR DESCRIPTION
**Pull request by lparsons**
Fixes #29

### CODE REVIEW

**Comment by joshuagryphon** [comment]
Thank you for submitting this so quickly.

Status update on this- I'm testing your changes locally (I really need to set up CI Here), and merging into `develop`. In general, the workflow for most PRs should be:

1. Branch made from `develop`
2. Changes made in `branch`
3. PR to merge `branch → develop`
4. Changes accumulate in `develop` until release bump time
5. At release bump time, merge `develop → master`
6. Version bump `master` and release to PyPI

**Comment by lparsons** [comment]
Ah, sorry, didn't realize you had a `develop` branch. I'll do that next time.

**Comment by joshuagryphon** [comment]
No worries! This is on me. Our dev policy in the docs is totally unclear

**Comment by joshuagryphon** [comment]
Btw thanks again for contributions & support. I clearly haven't had a lot of time to work on this in the last few years — I'm realiziing 0.4.8 was 2017 – and it's great to have your help

**Comment by joshuagryphon** [comment]
Ok! I merged this manually into `develop` and resolved some conflicts in 5be1317b779e39bb9f49d4145fa4a8d4d7c1e393, so closing here.

**Pull request closed without merging**
